# Generated by Django 3.2.9 on 2021-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('views', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=100)),
            ],
        ),
    ]
