# Generated by Django 3.2.9 on 2021-12-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialComp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('QueryId', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('brand1', models.CharField(max_length=100)),
                ('brand2', models.CharField(max_length=100)),
                ('brand3', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
