# Generated by Django 3.2.9 on 2021-12-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialComp', '0002_querymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='endDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='querymodel',
            name='startDate',
            field=models.CharField(max_length=100),
        ),
    ]
