# Generated by Django 3.2.8 on 2021-12-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialComp', '0005_postmodel_queryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel_Pinterest',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('QueryId', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('date', models.CharField(max_length=100)),
                ('emojis', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=300)),
                ('followers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel_TikTok',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('QueryId', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=300)),
                ('playUrl', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('date', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=200)),
                ('views', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=100)),
                ('shares', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel_Twitter',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('QueryId', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('date', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=300)),
                ('retweets', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=300)),
                ('views', models.CharField(max_length=100)),
                ('followers', models.CharField(max_length=100)),
            ],
        ),
    ]
